services:
  rag-backend:
    build: .
    container_name: rag_api_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./chroma_db:/app/chroma_db
    restart: unless-stopped